export const INTERNAL_LINKS = {
    tr: [
        { keyword: 'İstanbul', url: '/tr/rehber/istanbul' },
        { keyword: 'İstanbul\'da', url: '/tr/rehber/istanbul' },
        { keyword: 'İstanbul\'a', url: '/tr/rehber/istanbul' },
        { keyword: 'Türkiye', url: '/tr/rehber/turkey-guide' },
        { keyword: 'Türkiye\'de', url: '/tr/rehber/turkey-guide' },
        { keyword: 'Türkiye\'ye', url: '/tr/rehber/turkey-guide' },
        { keyword: 'Kapadokya', url: '/tr/rehber/cappadocia' },
        { keyword: 'Kapadokya\'da', url: '/tr/rehber/cappadocia' },
        { keyword: 'Kapadokya\'ya', url: '/tr/rehber/cappadocia' },
        { keyword: 'Antalya', url: '/tr/rehber/antalya' },
        { keyword: 'Antalya\'da', url: '/tr/rehber/antalya' },
        { keyword: 'Antalya\'ya', url: '/tr/rehber/antalya' },
        { keyword: 'Bodrum', url: '/tr/rehber/bodrum' },
        { keyword: 'Bodrum\'da', url: '/tr/rehber/bodrum' },
        { keyword: 'Bodrum\'a', url: '/tr/rehber/bodrum' },
        { keyword: 'Fethiye', url: '/tr/rehber/fethiye' },
        { keyword: 'Fethiye\'de', url: '/tr/rehber/fethiye' },
        { keyword: 'Fethiye\'ye', url: '/tr/rehber/fethiye' },
        { keyword: 'Ölüdeniz', url: '/tr/rehber/fethiye' }, // Synonyms
        { keyword: 'Likya Yolu', url: '/tr/rehber/fethiye' },
        { keyword: 'Şirince', url: '/tr/rehber/sirince' },
        { keyword: 'Şirince\'de', url: '/tr/rehber/sirince' },
        { keyword: 'Şirince\'ye', url: '/tr/rehber/sirince' },
        { keyword: 'Efes', url: '/tr/rehber/sirince' }, // Closest context
        { keyword: 'Sapanca', url: '/tr/rehber/sapanca' },
        { keyword: 'Sapanca\'da', url: '/tr/rehber/sapanca' },
        { keyword: 'Sapanca\'ya', url: '/tr/rehber/sapanca' },
    ],
    en: [
        { keyword: 'Istanbul', url: '/en/guide/istanbul' },
        { keyword: 'Constantinople', url: '/en/guide/istanbul' },
        { keyword: 'Turkey', url: '/en/guide/turkey-guide' },
        { keyword: 'Cappadocia', url: '/en/guide/cappadocia' },
        { keyword: 'Goreme', url: '/en/guide/cappadocia' },
        { keyword: 'Antalya', url: '/en/guide/antalya' },
        { keyword: 'Bodrum', url: '/en/guide/bodrum' },
        { keyword: 'Halicarnassus', url: '/en/guide/bodrum' },
        { keyword: 'Fethiye', url: '/en/guide/fethiye' },
        { keyword: 'Oludeniz', url: '/en/guide/fethiye' },
        { keyword: 'Blue Lagoon', url: '/en/guide/fethiye' },
        { keyword: 'Lycian Way', url: '/en/guide/fethiye' },
        { keyword: 'Sirince', url: '/en/guide/sirince' },
        { keyword: 'Ephesus', url: '/en/guide/sirince' },
        { keyword: 'Sapanca', url: '/en/guide/sapanca' },
    ]
};
