-- Populate article_media with localized alt tags
-- Generated by Antigravity

INSERT INTO public.article_media (url, alt_tr, alt_en)
VALUES
    ('/images/blog/camlik-museum-overview.png', 'Çamlık Buharlı Lokomotif Müzesi Genel Görünüm', 'General View of Camlik Steam Locomotive Museum'),
    ('/images/blog/camlik-family-walking.png', 'Müzede Ailece Yürüyüş', 'Family Walking in the Museum'),
    ('/images/blog/camlik-locomotive-detail.png', 'Lokomotif Detayları', 'Steam Locomotive Details'),
    ('/images/blog/camlik-historical-wagon.png', 'Tarihi Vagon', 'Historical Wagon Display')
ON CONFLICT (url) DO UPDATE SET
    alt_tr = EXCLUDED.alt_tr,
    alt_en = EXCLUDED.alt_en;
